spring.application.name=buddy
spring.ai.google.genai.api-key=${GEMINI_API_KEY}
server.port=8765
spring.ai.google.genai.chat.options.model=gemini-2.5-flash

spring.ai.retry.initial-interval=3000
spring.ai.retry.max-attempts=3

# Rate Limiter Configuration
resilience4j.ratelimiter.instances.buddyLimiter.limit-for-period=5
resilience4j.ratelimiter.instances.buddyLimiter.limit-refresh-period=1m
resilience4j.ratelimiter.instances.buddyLimiter.timeout-duration=0